parameters:
- name: script_repo
  type: string
- name: private_modules
  type: string
- name: public_modules
  type: string
- name: azdofeed
  type: string
- name: service_connection
  type: string
- name: api_token
  type: string
- name: domain_names
  type: string
- name: contact_email_address
  type: string
- name: storage_account_id
  type: string
- name: key_vault_id
  type: string
- name: dns_provider
  type: string
- name: environment_subscription_id
  type: string
- name: staging
  type: string
  default: 1

jobs:
- job: issue_or_renew_certificate
  displayName: "Issue or renew certificate"
  steps:
  - checkout: ${{ parameters.script_repo }}
  - template: ../tasks/install_modules.yml
    parameters:
      private_modules: ${{ parameters.private_modules }}
      public_modules: ${{ parameters.public_modules }}
      azdofeed: ${{ parameters.azdofeed }}
  - template: ../tasks/issue_renew_certificates.yml
    parameters:
      service_connection: ${{ parameters.service_connection }}
      api_token: ${{ parameters.api_token }}
      domain_names: ${{ parameters.domain_names }}
      contact_email_address: ${{ parameters.contact_email_address }}
      storage_account_id: ${{ parameters.storage_account_id }}
      key_vault_id: ${{ parameters.key_vault_id }}
      dns_provider: ${{ parameters.dns_provider }}
      environment_subscription_id: ${{ parameters.environment_subscription_id }}
      staging: ${{ parameters.staging }}