parameters:
- name: image_repository
  type: string
- name: dockerfile_path
  type: string
- name: service_connection
  type: string
- name: acr
  type: string
- name: tags
  type: string
  default: 'latest'

steps:
  - task: Docker@2
    displayName: Build Docker Image from Dockerfile
    inputs:
      containerRegistry: ${{ parameters.service_connection }}
      command: build
      arguments: --build-arg acr=${{ parameters.acr }} --build-arg tag=${{ parameters.tags }}
      dockerfile: ${{ dockerfile_path }}
      repository: ${{ image_repository }}
      tags: ${{ parameters.tags }}

  - task: Docker@2
    displayName: Push an image to container registry
    inputs:
      containerRegistry: ${{ parameters.service_connection }}
      command: push
      repository: ${{ image_repository }}
      tags: ${{ parameters.tags }}