parameters:
- name: storage_account
  type: string
- name: operation
  type: string
  values:
  - Add
  - Remove

steps:
- task: Bash@3
  condition: always()
  displayName: 'Update ${{ parameters.storage_account }} acl'
  inputs:
    failOnStdErr: true
    script: |

      # Update the Key Vault ACL
      case ${{ parameters.operation }} in
        Add)
          PARAMS="add --account-name ${{ parameters.storage_account }} --ip-address $(getip.IPADDR)"
        ;;

        Remove)
          PARAMS="remove --account-name ${{ parameters.storage_account }} --ip-address $(getip.IPADDR)"
        ;;
      esac

      az storage account network-rule $PARAMS > /dev/null 2>&1    

      echo "Pausing for 60 seconds to ensure Key Vault ACL has been updated"
      sleep 60
  
    targetType: 'inline'